name: sdui_renderer_example
description: Example app for the sdui_renderer Flutter SDK.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  sdui_renderer:
    path: ..

flutter:
  uses-material-design: true
